services:
  soloviov-demo-web-proxy:
    hostname: soloviov-demo-web-proxy
    depends_on:
      short-time-code:
        condition: service_started
      action-request:
        condition: service_started
      soloviov-demo-frontend:
        condition: service_started
      the-page-backend:
        condition: service_started
      the-page-frontend:
        condition: service_started
    build:
      dockerfile: ./soloviov-demo-web-proxy/dev.Dockerfile
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./soloviov-demo-web-proxy/nginx.default.conf:/etc/nginx/conf.d/default.conf:ro

  short-time-code:
    hostname: short-time-code
    build:
      dockerfile: ./short-time-code/dev.Dockerfile
    restart: always
    ports:
      - 9230:9229
    volumes:
      - ./short-time-code/src:/src
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80

  action-request:
    hostname: action-request
    build:
      dockerfile: ./action-request/dev.Dockerfile
    restart: always
    ports:
      - 9231:9229
    volumes:
      - ./action-request/src:/src
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80
      SHORT_TIME_CODE_API_ORIGIN: http://short-time-code:80

  soloviov-demo-frontend:
    hostname: soloviov-demo-frontend
    build:
      dockerfile: ./soloviov-demo-frontend/dev.Dockerfile
    restart: always
    ports:
      - 9232:9229
    volumes:
      - ./soloviov-demo-frontend/src:/src
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80

  the-page-mongo:
    hostname: the-page-mongo
    image: mongo:5.0.28
    restart: always
    environment:
      MONGO_INITDB_DATABASE: the-page
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./mongo_data/db:/data/db
      - ./mongo_data/configdb:/data/configdb

  the-page-mongo-express:
    hostname: the-page-mongo-express
    depends_on:
      the-page-mongo:
        condition: service_healthy
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://the-page-mongo:27017/
      ME_CONFIG_MONGODB_SERVER: the-page-mongo
      ME_CONFIG_MONGODB_HOST: the-page-mongo
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_BASICAUTH_FILE: /run/secrets/the_page_me_config_basicauth
      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/the_page_me_config_basicauth_username
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/the_page_me_config_basicauth_password
    secrets:
      - the_page_me_config_basicauth
      - the_page_me_config_basicauth_username
      - the_page_me_config_basicauth_password

  the-page-backend:
    hostname: the-page-backend
    depends_on:
      the-page-mongo:
        condition: service_healthy
    build:
      dockerfile: ./the-page/backend/dev.Dockerfile
    restart: always
    ports:
      - 9233:9229
    volumes:
      - ./the-page/backend/src:/src
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/the_page_mongo_uri
      MONGO_HEARTBEAT_FREQUENCY_MS: 60000
      JWT_SECRET_FILE: /run/secrets/the_page_backend_gwt_secret
      APP_BASE_PATH: /the-page-backend/
      FRONTEND_BASE_URL: /the-page-frontend
    secrets:
      - the_page_backend_gwt_secret
      - the_page_mongo_uri

  the-page-frontend:
    hostname: the-page-frontend
    depends_on:
      the-page-mongo:
        condition: service_healthy
    build:
      dockerfile: ./the-page/frontend/dev.Dockerfile
    restart: always
    ports:
      - 9234:9229
    volumes:
      - ./the-page/frontend/src:/src
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/the_page_mongo_uri
      MONGO_HEARTBEAT_FREQUENCY_MS: 60000
      APP_BASE_HOSTNAME: thepage.local
    secrets:
      - the_page_mongo_uri

secrets:
  the_page_me_config_basicauth:
    file: the_page_me_config_basicauth.txt
  the_page_me_config_basicauth_username:
    file: the_page_me_config_basicauth_username.txt
  the_page_me_config_basicauth_password:
    file: the_page_me_config_basicauth_password.txt
  the_page_mongo_uri:
    file: the_page_mongo_uri.txt
  the_page_backend_gwt_secret:
    file: the_page_backend_gwt_secret.txt
