services:
  soloviov-demo-web-proxy:
    hostname: soloviov-demo-web-proxy
    build:
      dockerfile: ./soloviov-demo-web-proxy/dev.Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./soloviov-demo-web-proxy/nginx.default.conf:/etc/nginx/conf.d/default.conf:ro

  short-time-code:
    hostname: short-time-code
    build:
      dockerfile: ./short-time-code/dev.Dockerfile
    ports:
      - 9230:9229
    volumes:
      - ./short-time-code/src:/src
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80

  action-request:
    hostname: action-request
    build:
      dockerfile: ./action-request/dev.Dockerfile
    ports:
      - 9231:9229
    volumes:
      - ./action-request/src:/src
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80
      SHORT_TIME_CODE_API_ORIGIN: http://short-time-code:80

  soloviov-demo-frontend:
    hostname: soloviov-demo-frontend
    build:
      dockerfile: ./soloviov-demo-frontend/dev.Dockerfile
    ports:
      - 9232:9229
    volumes:
      - ./soloviov-demo-frontend/src:/src
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80

  the-page-backend:
    hostname: the-page-backend
    build:
      dockerfile: ./the-page/backend/dev.Dockerfile
    ports:
      - 9233:9229
    volumes:
      - ./the-page/backend/src:/src
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/the_page_mongo_uri
      JWT_SECRET_FILE: /run/secrets/the_page_backend_gwt_secret
      APP_BASE_PATH: /the-page-backend/
      FRONTEND_BASE_URL: /the-page-frontend
    secrets:
      - the_page_backend_gwt_secret
      - the_page_mongo_uri

  the-page-frontend:
    hostname: the-page-frontend
    build:
      dockerfile: ./the-page/frontend/dev.Dockerfile
    ports:
      - 9234:9229
    volumes:
      - ./the-page/frontend/src:/src
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/the_page_mongo_uri
      APP_BASE_HOSTNAME: thepage.local
    secrets:
      - the_page_mongo_uri

secrets:
  the_page_mongo_uri:
    file: the_page_mongo_uri.txt
  the_page_backend_gwt_secret:
    file: the_page_backend_gwt_secret.txt
